# Generated by Django 4.0.4 on 2022-05-31 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urls',
            options={'verbose_name_plural': 'Urls'},
        ),
    ]
