# Generated by Django 4.0.4 on 2022-05-31 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_alter_urls_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urls',
            options={'verbose_name_plural': 'URLS'},
        ),
        migrations.AlterField(
            model_name='urls',
            name='alias',
            field=models.URLField(editable=False, max_length=6, unique=True),
        ),
    ]
