# Generated by Django 4.0.4 on 2022-05-31 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_alter_urls_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='long_url',
            field=models.CharField(max_length=2048, unique=True),
        ),
    ]
