# Generated by Django 4.0.4 on 2022-06-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0006_alter_urls_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='alias',
            field=models.URLField(editable=False, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='urls',
            name='long_url',
            field=models.CharField(max_length=2048),
        ),
    ]
